"""add document classification fields

Revision ID: 500ccd6c3dab
Revises: 9f0f863f9c88
Create Date: 2026-08-13 20:02:45.663137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500ccd6c3dab'
down_revision: Union[str, Sequence[str], None] = '9f0f863f9c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('classified_type', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('classification_reasoning', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('classification_topic', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('classification_action_required', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('classification_result_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'classification_result_json')
    op.drop_column('documents', 'classification_action_required')
    op.drop_column('documents', 'classification_topic')
    op.drop_column('documents', 'classification_reasoning')
    op.drop_column('documents', 'classification_confidence')
    op.drop_column('documents', 'classified_type')
    # ### end Alembic commands ###
