"""add api_call_logs table

Revision ID: 52a5de440ca7
Revises: 7edba56d59a9
Create Date: 2026-08-14 09:35:31.586066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a5de440ca7'
down_revision: Union[str, Sequence[str], None] = '7edba56d59a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('anonymized_prompt_id', sa.String(length=64), nullable=True),
    sa.Column('result_status', sa.String(length=32), nullable=False),
    sa.Column('error_status', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
