"""add input output tokens and estimated cost to api call log

Revision ID: 5ce0d7e04699
Revises: 16884fc4ddb0
Create Date: 2026-08-16 06:58:56.924413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce0d7e04699'
down_revision: Union[str, Sequence[str], None] = '16884fc4ddb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_call_logs', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('api_call_logs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('api_call_logs', sa.Column('estimated_cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_call_logs', 'estimated_cost_usd')
    op.drop_column('api_call_logs', 'output_tokens')
    op.drop_column('api_call_logs', 'input_tokens')
    # ### end Alembic commands ###
