"""add outbox_entries table

Revision ID: ceabf73d4cf4
Revises: eb9a1d50c43f
Create Date: 2026-08-15 02:08:26.698637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceabf73d4cf4'
down_revision: Union[str, Sequence[str], None] = 'eb9a1d50c43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_entries',
    sa.Column('matter_id', sa.String(), nullable=False),
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_entries_draft_id'), 'outbox_entries', ['draft_id'], unique=True)
    op.create_index(op.f('ix_outbox_entries_matter_id'), 'outbox_entries', ['matter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_entries_matter_id'), table_name='outbox_entries')
    op.drop_index(op.f('ix_outbox_entries_draft_id'), table_name='outbox_entries')
    op.drop_table('outbox_entries')
    # ### end Alembic commands ###
