"""extend sources with document_date and provider_name

Revision ID: d09ccd7d2f36
Revises: ace879814d10
Create Date: 2026-08-14 04:11:23.421668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09ccd7d2f36'
down_revision: Union[str, Sequence[str], None] = 'ace879814d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('document_date', sa.Date(), nullable=True))
    op.add_column('sources', sa.Column('provider_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'provider_name')
    op.drop_column('sources', 'document_date')
    # ### end Alembic commands ###
