"""add sessions_invalidated_after to users

Revision ID: da7a5ed47e28
Revises: 4e15e8bb50a1
Create Date: 2026-08-15 13:59:07.968872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7a5ed47e28'
down_revision: Union[str, Sequence[str], None] = '4e15e8bb50a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sessions_invalidated_after', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessions_invalidated_after')
    # ### end Alembic commands ###
