"""add draft source and knowledge item reference links

Revision ID: eb9a1d50c43f
Revises: f696903b174e
Create Date: 2026-08-15 01:48:36.594741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9a1d50c43f'
down_revision: Union[str, Sequence[str], None] = 'f696903b174e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_knowledge_item_links',
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('knowledge_item_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_knowledge_item_links_draft_id'), 'draft_knowledge_item_links', ['draft_id'], unique=False)
    op.create_index(op.f('ix_draft_knowledge_item_links_knowledge_item_id'), 'draft_knowledge_item_links', ['knowledge_item_id'], unique=False)
    op.create_table('draft_source_links',
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_source_links_draft_id'), 'draft_source_links', ['draft_id'], unique=False)
    op.create_index(op.f('ix_draft_source_links_source_id'), 'draft_source_links', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_source_links_source_id'), table_name='draft_source_links')
    op.drop_index(op.f('ix_draft_source_links_draft_id'), table_name='draft_source_links')
    op.drop_table('draft_source_links')
    op.drop_index(op.f('ix_draft_knowledge_item_links_knowledge_item_id'), table_name='draft_knowledge_item_links')
    op.drop_index(op.f('ix_draft_knowledge_item_links_draft_id'), table_name='draft_knowledge_item_links')
    op.drop_table('draft_knowledge_item_links')
    # ### end Alembic commands ###
